# The URL the site will be built for
base_url = "https://brianopdedijk.nl"

# The title of the site
title = "Brian op de Dijk"

#Theme
theme = "clean-blog"
taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

#Build RSS feed
generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Brian"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/nieuws", name = "Nieuws"},
    {url = "$BASE_URL/biografie", name = "Biografie"},    
    {url = "$BASE_URL/muziek", name = "Muziek"},
    {url = "$BASE_URL/contact", name = "Contact"},
]
clean_blog_social = [
    {url = "https://www.youtube.com/c/brianopdedijk", icon="fab fa-youtube"},
    {url = "https://www.tiktok.com/@acteerenleer", icon="fab fa-tiktok"},
    {url = "https://www.imdb.com/name/nm7289280/", icon="fab fa-imdb"},
    {url = "https://www.linkedin.com/in/brian-op-de-dijk-aa05553b/", icon="fab fa-linkedin"},
    {url = "https://www.linktr.ee/brianopdedijk", icon="fas fa-tree"},
    {url = "$BASE_URL/rss.xml", icon="fa fa-rss"},
]
